- name: printing variables
  hosts: all
  become: yes
  tasks:
  - name: print variables 
    vars:
      username: centos
      homedir: /home/centos
    tasks:
      - name: print variables
        ansible.builtin.debug:
          msg: "The user is {{username}} and homedirectory is {{homedir}} "  