- name: printing the variables
  become: yes
  hosts: localhost
  vars:
    name: praneeth
    lastname: REDDY
  tasks:
  - name: playlevel variables
    ansible.builtin.debug:
      msg: "I am {{name}} and my caste is {{lastname}}"