- name: getting variables from a file
  hosts: localhost
  vars_files:
    - storing variables in a file.yaml
  tasks:
    - name: getting
      ansible.builtin.debug:
        msg: "i am printing {{hero}}"
