- name: getting variables from a file
  hosts: localhost
  var_files:
    - storng variables in a file.yaml
  tasks:
    - name: getting
      ansible.builtin.debug:
      msg: "i am printing {{hero}}"
